"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {ArrowLeft,Package,ShoppingBag,Users,CircleDollarSign,Save,RotateCcw,Plus,Trash2,BarChart3,History,Truck} from "lucide-react";
import {products} from "../products";
import {useStore} from "../store";
const money=n=>new Intl.NumberFormat("tr-TR",{style:"currency",currency:"TRY",maximumFractionDigits:0}).format(Number(n)||0);
const statuses=["Sipariş alındı","Hazırlanıyor","Kargoya verildi","Teslim edildi","İptal edildi"];
const paymentStatuses=["Bekliyor","Ödendi","Başarısız","İade Edildi"];
const carriers=["HepsiJET","Trendyol Express","Yurtiçi Kargo","Aras Kargo","Sürat Kargo","PTT Kargo","DHL eCommerce","UPS","Horoz","CEVA","Kolay Gelsin","Diğer"];
export default function Admin(){
 const {orders,productOverrides,customProducts,deletedProducts,serverReady,saveProductOverride,resetProductOverride,addProduct,deleteProduct,restoreProduct,updateOrderStatus}=useStore();
 const [tab,setTab]=useState("dashboard"),[rows,setRows]=useState([]),[showAdd,setShowAdd]=useState(false),[form,setForm]=useState({name:"",code:"",category:"Kurutmalıklar",price:"",stock:0,discount:0,description:""}),[sqlCustomers,setSqlCustomers]=useState([]),[stockQty,setStockQty]=useState({}),[stockNote,setStockNote]=useState({}),[stockLog,setStockLog]=useState([]),[shipment,setShipment]=useState({}),[shippingBusy,setShippingBusy]=useState({}),[shippingProviders,setShippingProviders]=useState([]);
 const all=[...products,...customProducts].filter((p,i,a)=>a.findIndex(x=>x.slug===p.slug)===i);
 useEffect(()=>setRows(all.map(p=>{const o=productOverrides[p.slug]||{};return {...p,...o,discount:o.discount??0,stock:o.stock??0,active:o.active??true,deleted:deletedProducts.includes(p.slug)}})),[productOverrides,customProducts,deletedProducts]);
 useEffect(()=>{if(tab!=="customers")return;fetch("/api/customers",{cache:"no-store"}).then(r=>r.ok?r.json():Promise.reject()).then(d=>setSqlCustomers(d.customers||[])).catch(()=>setSqlCustomers([]))},[tab]);
 useEffect(()=>{if(tab!=="stock")return;fetch("/api/stock",{cache:"no-store"}).then(r=>r.ok?r.json():Promise.reject()).then(d=>setStockLog(d.movements||[])).catch(()=>setStockLog([]))},[tab]);
 useEffect(()=>{fetch("/api/shipping/providers",{cache:"no-store"}).then(r=>r.ok?r.json():Promise.reject()).then(d=>setShippingProviders(d.providers||[])).catch(()=>setShippingProviders([]))},[]);
 const changeStock=async slug=>{const qty=Number(stockQty[slug]||0);if(!qty)return;const r=await fetch("/api/stock",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({slug,quantity:qty,note:stockNote[slug]||"Admin stok hareketi"})});const d=await r.json();if(r.ok){setRows(x=>x.map(p=>p.slug===slug?{...p,stock:d.newStock}:p));setStockQty(x=>({...x,[slug]:""}));setStockNote(x=>({...x,[slug]:""}));const log=await fetch("/api/stock",{cache:"no-store"}).then(x=>x.json()).catch(()=>({movements:[]}));setStockLog(log.movements||[])}else alert(d.error||"Stok hareketi kaydedilemedi")};
 const revenue=orders.reduce((s,o)=>s+(Number(o.total)||0),0);const units=orders.reduce((s,o)=>s+(o.items||[]).reduce((a,i)=>a+i.qty,0),0);const activeCount=rows.filter(x=>x.active&&!x.deleted).length;
 const customers=useMemo(()=>{const m=new Map();orders.forEach(o=>{if(o.customer?.email)m.set(o.customer.email,{...o.customer,orders:(m.get(o.customer.email)?.orders||0)+1,total:(m.get(o.customer.email)?.total||0)+(Number(o.total)||0)})});return [...m.values()]},[orders]);
 const daily=useMemo(()=>{const days=[];for(let i=6;i>=0;i--){const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-i);const key=d.toISOString().slice(0,10);days.push({label:d.toLocaleDateString('tr-TR',{weekday:'short'}),value:orders.filter(o=>o.createdAt?.slice(0,10)===key).reduce((s,o)=>s+(Number(o.total)||0),0)})}return days},[orders]);
 const update=(slug,key,value)=>setRows(r=>r.map(x=>x.slug===slug?{...x,[key]:value}:x));
 const save=row=>saveProductOverride(row.slug,{price:row.price===''?null:Number(row.price),stock:Number(row.stock)||0,discount:Number(row.discount)||0,active:row.active});
 const submitAdd=e=>{e.preventDefault();const p=addProduct(form);saveProductOverride(p.slug,{stock:Number(form.stock)||0,discount:Number(form.discount)||0,active:true});setForm({name:"",code:"",category:"Kurutmalıklar",price:"",stock:0,discount:0,description:""});setShowAdd(false);setTab('products')};
 const setShipmentField=(id,key,value)=>setShipment(s=>({...s,[id]:{...(s[id]||{}),[key]:value}}));
 const saveOrder=(order,status,paymentStatus)=>{const s=shipment[order.id]||{};updateOrderStatus(order.OrderNo||order.id,status||order.status,{carrier:s.carrier??order.carrier??"",trackingNumber:s.trackingNumber??order.trackingNumber??"",paymentStatus:paymentStatus??order.PaymentStatus??order.paymentStatus??"Bekliyor"})};
 const createShipment=async order=>{
  const orderNo=String(order.OrderNo||order.id||"").trim();const carrier=String((shipment[order.id]?.carrier??order.carrier??"")).trim();
  if(!orderNo)return alert("Sipariş numarası bulunamadı.");if(!carrier)return alert("Önce kargo firması seçin.");
  const provider=shippingProviders.find(p=>p.name===carrier);if(!provider?.create)return alert(`${carrier} için resmi gönderi oluşturma API'si henüz etkin değil.`);if(provider.configured===false)return alert(`${carrier} API bilgileri sunucu ortamında tanımlı değil.`);
  setShippingBusy(x=>({...x,[order.id]:true}));
  try{const a=order.shippingAddress||order.ShippingAddress||{};const customer=order.customer||{};const items=Array.isArray(order.items)?order.items:[];const pieceCount=Math.max(1,items.reduce((sum,item)=>sum+Math.max(0,Number(item.qty)||0),0));
   const r=await fetch("/api/shipping/create",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({carrier,orderNo,ShippingAddress:a,ReceiverName:a.name||customer.name||order.ReceiverName||"",AddressLine:a.address||a.AddressLine||order.AddressLine||customer.address||"",Phone:a.phone||order.Phone||customer.phone||"",City:a.city||a.City||order.City||"",District:a.district||a.District||order.District||"",PostalCode:a.postalCode||a.PostalCode||order.PostalCode||"",pieceCount,weight:Number(order.weight||1)})});
   const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error(d.error||`${carrier} gönderisi oluşturulamadı.`);
   const trackingNumber=d.trackingNumber||d.invoiceKey||"";setShipmentField(order.id,"trackingNumber",trackingNumber);updateOrderStatus(orderNo,"Kargoya verildi",{carrier,trackingNumber});
   alert(`${carrier} gönderisi oluşturuldu.\nTakip no: ${trackingNumber||"oluşturulmadı"}${d.barcode?`\nBarkod: ${d.barcode}`:""}`);
  }catch(e){alert(e?.message||"Kargo gönderisi oluşturulamadı.")}finally{setShippingBusy(x=>({...x,[order.id]:false}))}
 };
 return <main className="admin-page"><header><Link href="/" className="back-link"><ArrowLeft size={15}/> Mağazaya dön</Link><small>ALYA HOMES / YÖNETİM</small><div className="admin-sync"><i className={serverReady?"online":"offline"}></i>{serverReady?"Sunucu verisi aktif":"Yerel mod"}</div><h1>Mağaza paneli</h1></header>
 <section className="admin-stats"><div><ShoppingBag/><span>Sipariş</span><strong>{orders.length}</strong></div><div><CircleDollarSign/><span>Ciro</span><strong>{money(revenue)}</strong></div><div><Package/><span>Satılan adet</span><strong>{units}</strong></div><div><Users/><span>Aktif ürün</span><strong>{activeCount}</strong></div></section>
 <nav className="admin-tabs">{[['dashboard','Dashboard'],['products','Ürünler'],['stock','Stok'],['orders','Siparişler'],['customers','Müşteriler']].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</nav>
 {tab==='dashboard'&&<section className="admin-dashboard"><div className="admin-panel"><div className="admin-table-head"><div><h2>Son 7 gün</h2><span>Gerçekleşmiş sipariş kayıtlarına göre</span></div><BarChart3/></div><div className="bar-chart">{daily.map(d=><div className="bar-col" key={d.label}><span>{money(d.value)}</span><div className="bar-track"><i style={{height:`${daily.some(x=>x.value)?Math.max(4,(d.value/Math.max(...daily.map(x=>x.value),1))*100):4}%`}}/></div><small>{d.label}</small></div>)}</div></div><div className="admin-panel"><div className="admin-table-head"><h2>Sipariş durumları</h2><span>{orders.length} toplam</span></div><div className="status-list">{statuses.map(s=><div key={s}><span>{s}</span><strong>{orders.filter(o=>o.status===s).length}</strong></div>)}</div></div></section>}
 {tab==='products'&&<section className="admin-products"><div className="admin-table-head"><div><h2>Ürün yönetimi</h2><span>Fiyat, stok, indirim, yayın ve ürün yaşam döngüsünü yönet.</span></div><button className="admin-primary" onClick={()=>setShowAdd(true)}><Plus size={15}/> Yeni ürün</button></div><div className="admin-product-head"><span>Ürün</span><span>Fiyat</span><span>Stok</span><span>İndirim %</span><span>Yayın</span><span></span></div>{rows.map(row=><article className={`admin-product-row ${row.deleted?'is-deleted':''}`} key={row.slug}><div className="admin-product-name"><img src={row.image} alt=""/><div><strong>{row.name}</strong><span>{row.code} · {row.category}</span></div></div><input aria-label="Fiyat" value={row.price??''} onChange={e=>update(row.slug,'price',e.target.value)} placeholder="₺" disabled={row.deleted}/><input aria-label="Stok" type="number" min="0" value={row.stock} onChange={e=>update(row.slug,'stock',e.target.value)} disabled={row.deleted}/><input aria-label="İndirim" type="number" min="0" max="100" value={row.discount} onChange={e=>update(row.slug,'discount',e.target.value)} disabled={row.deleted}/><label className="switch"><input type="checkbox" checked={row.active&&!row.deleted} onChange={e=>update(row.slug,'active',e.target.checked)} disabled={row.deleted}/><span></span></label><div className="admin-row-actions">{row.deleted?<button onClick={()=>restoreProduct(row.slug)} title="Geri yükle"><RotateCcw size={15}/></button>:<><button onClick={()=>save(row)} title="Kaydet"><Save size={15}/></button><button onClick={()=>resetProductOverride(row.slug)} title="Varsayılana dön"><RotateCcw size={15}/></button><button onClick={()=>deleteProduct(row.slug)} title="Ürünü kaldır"><Trash2 size={15}/></button></>}</div></article>)}</section>}
 {tab==='stock'&&<section className="admin-products"><div className="admin-table-head"><div><h2>Stok yönetimi</h2><span>Stok giriş ve çıkışlarını hareket kaydıyla yönet.</span></div><History/></div><div className="stock-grid">{rows.filter(r=>!r.deleted).map(r=><article className="stock-card" key={r.slug}><div className="admin-product-name"><img src={r.image} alt=""/><div><strong>{r.name}</strong><span>{r.code} · Mevcut: {r.stock||0}</span></div></div><input type="number" value={stockQty[r.slug]??""} onChange={e=>setStockQty(x=>({...x,[r.slug]:e.target.value}))} placeholder="+ giriş / - çıkış"/><input value={stockNote[r.slug]??""} onChange={e=>setStockNote(x=>({...x,[r.slug]:e.target.value}))} placeholder="Açıklama"/><button className="admin-primary" onClick={()=>changeStock(r.slug)}>Kaydet</button></article>)}</div><div className="stock-history"><h3>Son hareketler</h3>{stockLog.slice(0,30).map(m=><div key={m.Id}><span>{m.ProductSlug}</span><b className={Number(m.Quantity)>0?'in':'out'}>{Number(m.Quantity)>0?'+':''}{m.Quantity}</b><span>{m.PreviousStock} → {m.NewStock}</span><small>{m.Note||''}</small></div>)}</div></section>}
 {tab==='orders'&&<section className="admin-table"><div className="admin-table-head"><div><h2>Siparişler</h2><span>{orders.length} sipariş</span></div><Truck/></div>{!orders.length?<p className="admin-empty">Henüz sipariş bulunmuyor.</p>:orders.map(o=>{const s=shipment[o.id]||{};const carrier=s.carrier??o.carrier??"";const busy=Boolean(shippingBusy[o.id]);const provider=shippingProviders.find(p=>p.name===carrier);const paymentStatus=o.PaymentStatus||o.paymentStatus||"Bekliyor";return <article key={o.id}><div><strong>{o.OrderNo||o.id}</strong><span>{o.customer?.name} · {o.customer?.email}</span><div className="shipment-admin-fields"><select aria-label="Kargo firması" value={carrier} onChange={e=>setShipmentField(o.id,'carrier',e.target.value)}><option value="">Kargo firması seç</option>{carriers.map(c=><option key={c}>{c}</option>)}</select><input aria-label="Takip numarası" value={s.trackingNumber??o.trackingNumber??""} onChange={e=>setShipmentField(o.id,'trackingNumber',e.target.value)} placeholder="Takip numarası"/><button className="admin-primary" onClick={()=>saveOrder(o)}><Save size={14}/> Kargoyu kaydet</button>{provider?.create&&<button className="admin-primary" disabled={busy} onClick={()=>createShipment(o)}><Truck size={14}/>{busy?'Gönderi oluşturuluyor…':`${carrier} ile Kargo Oluştur`}</button>}</div>{(s.trackingNumber||o.trackingNumber)&&<small className="shipment-tracking-result">Takip: {s.trackingNumber||o.trackingNumber}</small>}</div><div className="order-admin-right"><select aria-label="Sipariş durumu" value={o.status} onChange={e=>saveOrder(o,e.target.value)}>{statuses.map(st=><option key={st}>{st}</option>)}</select><select aria-label="Ödeme durumu" value={paymentStatus} onChange={e=>saveOrder(o,o.status,e.target.value)}>{paymentStatuses.map(st=><option key={st}>{st}</option>)}</select><strong>{money(o.total)}</strong></div></article>})}</section>}
 {tab==='customers'&&<section className="admin-table"><div className="admin-table-head"><h2>Müşteriler</h2><span>{serverReady&&sqlCustomers.length?sqlCustomers.length:customers.length} müşteri</span></div>{serverReady&&sqlCustomers.length?sqlCustomers.map(c=><article key={c.Id}><div><strong>{[c.FirstName,c.LastName].filter(Boolean).join(' ')||'İsimsiz müşteri'}</strong><span>{c.Email} · {c.Phone||'Telefon yok'} · {[c.District,c.City].filter(Boolean).join(' / ')}</span></div><div><span>{c.Orders||0} sipariş</span><strong>{money(c.TotalSpent)}</strong></div></article>):!customers.length?<p className="admin-empty">Henüz müşteri bulunmuyor.</p>:customers.map(c=><article key={c.email}><div><strong>{c.name}</strong><span>{c.email} · {c.phone||'Telefon yok'}</span></div><div><span>{c.orders} sipariş</span><strong>{money(c.total)}</strong></div></article>)}</section>}
 {showAdd&&<div className="modal-backdrop" onClick={()=>setShowAdd(false)}><form className="admin-modal" onClick={e=>e.stopPropagation()} onSubmit={submitAdd}><button type="button" className="modal-close" onClick={()=>setShowAdd(false)}>×</button><small>ALYA HOMES</small><h2>Yeni ürün</h2><div className="admin-form-grid"><input required placeholder="Ürün adı" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input placeholder="Ürün kodu" value={form.code} onChange={e=>setForm({...form,code:e.target.value})}/><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option>Kurutmalıklar</option><option>Ütü Masaları</option><option>Yeni Kategori</option></select><input type="number" min="0" placeholder="Fiyat" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/><input type="number" min="0" placeholder="Stok" value={form.stock} onChange={e=>setForm({...form,stock:e.target.value})}/><input type="number" min="0" max="100" placeholder="İndirim %" value={form.discount} onChange={e=>setForm({...form,discount:e.target.value})}/></div><textarea placeholder="Açıklama" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><button className="admin-primary full" type="submit">Ürünü oluştur</button></form></div>}
 </main>