import { customerEmailFromRequest } from '../../../lib/customer-auth';
import { isAdminRequest, unauthorized } from '../../../lib/auth';
import sql from 'mssql';
export const runtime='nodejs'; export const dynamic='force-dynamic';
let poolPromise=null;
const configured=()=>Boolean(process.env.SQL_SERVER&&process.env.SQL_DATABASE&&process.env.SQL_USER&&process.env.SQL_PASSWORD);
async function pool(){if(!configured())return null;if(!poolPromise)poolPromise=sql.connect({server:process.env.SQL_SERVER,database:process.env.SQL_DATABASE,user:process.env.SQL_USER,password:process.env.SQL_PASSWORD,port:Number(process.env.SQL_PORT||1433),options:{encrypt:String(process.env.SQL_ENCRYPT||'false').toLowerCase()==='true',trustServerCertificate:String(process.env.SQL_TRUST_SERVER_CERTIFICATE||'true')}}).catch(e=>{poolPromise=null;throw e});return poolPromise}
export async function GET(req){const admin=await isAdminRequest(req);const own=admin?'':await customerEmailFromRequest(req);if(!admin&&!own)return unauthorized();try{const p=await pool();if(!p)return Response.json({source:'file',customers:[]});const {searchParams}=new URL(req.url);const email=admin?String(searchParams.get('email')||'').trim().toLowerCase():own;const q=new sql.Request(p);let r;if(email){r=await q.input('email',sql.NVarChar(320),email).query(`SELECT TOP 1 c.Id,c.Email,c.FirstName,c.LastName,c.Phone,c.AddressLine,c.City,c.District,c.PostalCode,c.CreatedAt,c.UpdatedAt,COUNT(o.Id) Orders,SUM(COALESCE(o.Total,0)) TotalSpent FROM dbo.AlyaCustomers c LEFT JOIN dbo.AlyaOrders o ON o.CustomerId=c.Id WHERE c.Email=@email GROUP BY c.Id,c.Email,c.FirstName,c.LastName,c.Phone,c.AddressLine,c.City,c.District,c.PostalCode,c.CreatedAt,c.UpdatedAt`);return Response.json({source:'sql',customer:r.recordset[0]||null},{headers:{'Cache-Control':'no-store'}})}r=await q.query(`SELECT c.Id,c.Email,c.FirstName,c.LastName,c.Phone,c.AddressLine,c.City,c.District,c.PostalCode,c.CreatedAt,c.UpdatedAt,COUNT(o.Id) Orders,SUM(COALESCE(o.Total,0)) TotalSpent FROM dbo.AlyaCustomers c LEFT JOIN dbo.AlyaOrders o ON o.CustomerId=c.Id GROUP BY c.Id,c.Email,c.FirstName,c.LastName,c.Phone,c.AddressLine,c.City,c.District,c.PostalCode,c.CreatedAt,c.UpdatedAt ORDER BY c.CreatedAt DESC`);return Response.json({source:'sql',customers:r.recordset},{headers:{'Cache-Control':'no-store'}})}catch(e){return Response.json({source:'error',customers:[]},{status:500})}}
export async function PATCH(req){const admin=await isAdminRequest(req);const own=admin?'':await customerEmailFromRequest(req);if(!admin&&!own)return unauthorized();try{const b=await req.json();const p=await pool();if(!p)return Response.json({error:'SQL bağlantısı yapılandırılmamış'},{status:503});
if(!admin){const f=(v,n)=>(v==null||v==='')?null:String(v).slice(0,n);const bind=(r)=>r.input('email',sql.NVarChar(320),own).input('first',sql.NVarChar(100),f(b.firstName,100)).input('last',sql.NVarChar(100),f(b.lastName,100)).input('phone',sql.NVarChar(50),f(b.phone,50)).input('address',sql.NVarChar(500),f(b.addressLine,500)).input('city',sql.NVarChar(100),f(b.city,100)).input('district',sql.NVarChar(100),f(b.district,100)).input('postal',sql.NVarChar(20),f(b.postalCode,20));const u=await bind(p.request()).query(`UPDATE dbo.AlyaCustomers SET FirstName=@first,LastName=@last,Phone=@phone,AddressLine=@address,City=@city,District=@district,PostalCode=@postal,UpdatedAt=SYSUTCDATETIME() WHERE Email=@email`);if(!u.rowsAffected[0])await bind(p.request()).query(`INSERT dbo.AlyaCustomers(Email,FirstName,LastName,Phone,AddressLine,City,District,PostalCode) VALUES(@email,@first,@last,@phone,@address,@city,@district,@postal)`);return Response.json({ok:true},{headers:{'Cache-Control':'no-store'}})}
if(!b.id)return Response.json({error:'id gerekli'},{status:400});await p.request().input('id',sql.BigInt,b.id).input('first',sql.NVarChar(100),b.firstName||null).input('last',sql.NVarChar(100),b.lastName||null).input('phone',sql.NVarChar(50),b.phone||null).input('address',sql.NVarChar(500),b.addressLine||null).input('city',sql.NVarChar(100),b.city||null).input('district',sql.NVarChar(100),b.district||null).input('postal',sql.NVarChar(20),b.postalCode||null).query(`UPDATE dbo.AlyaCustomers SET FirstName=@first,LastName=@last,Phone=@phone,AddressLine=@address,City=@city,District=@district,PostalCode=@postal,UpdatedAt=SYSUTCDATETIME() WHERE Id=@id`);return Response.json({ok:true,source:'sql'})}catch(e){return Response.json({error:'Müşteri güncellenemedi'},{status:500})}}
