"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {ArrowLeft,CheckCircle2,Truck,RefreshCw,ExternalLink,AlertTriangle} from "lucide-react";

export default function ShippingAdmin(){
 const [providers,setProviders]=useState([]),[orders,setOrders]=useState([]),[provider,setProvider]=useState('aras'),[orderNo,setOrderNo]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const load=async()=>{setBusy(true);try{const [p,o]=await Promise.all([fetch('/api/shipping',{cache:'no-store'}).then(r=>r.json()),fetch('/api/orders',{cache:'no-store'}).then(r=>r.json())]);setProviders(p.providers||[]);setOrders(o.orders||[]);}catch{setMessage('Kargo bilgileri alınamadı')}finally{setBusy(false)}};
 useEffect(()=>{load()},[]);
 const create=async()=>{if(!orderNo)return setMessage('Önce sipariş seç');setBusy(true);setMessage('Kargo servisine bağlanılıyor...');try{const r=await fetch('/api/shipping',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({provider,orderNo})});const d=await r.json();setMessage(r.ok?'Gönderi oluşturuldu':d.error||'Gönderi oluşturulamadı');}catch{setMessage('Kargo servisine erişilemedi')}finally{setBusy(false)}};
 return <main className="shipping-admin"><header><Link href="/admin" className="back"><ArrowLeft size={16}/> Yönetim paneline dön</Link><small>ALYA HOMES / KARGO ENTEGRASYONLARI</small><h1>Kargo entegrasyonları</h1><p>Trendyol veya Hepsiburada bağlantısı yok. ALYA HOMES, kargo firmalarının kendi kurumsal servislerine doğrudan bağlanır.</p></header>
 <section className="provider-grid">{providers.map(p=><article key={p.key} className={p.configured?'ready':''}><div className="provider-icon"><Truck size={20}/></div><div><h2>{p.name}</h2><span>{p.configured?'Kimlik bilgileri tanımlı':'API bilgileri bekleniyor'}</span></div>{p.configured?<CheckCircle2 className="ok" size={18}/>:<AlertTriangle className="warn" size={18}/>}</article>)}</section>
 <section className="shipping-card"><div className="card-head"><div><small>GÖNDERİ OLUŞTUR</small><h2>Siparişi kargoya aktar</h2></div><button onClick={load} disabled={busy}><RefreshCw size={15}/> Yenile</button></div><label>Kargo firması<select value={provider} onChange={e=>setProvider(e.target.value)}>{providers.map(p=><option key={p.key} value={p.key}>{p.name}{p.configured?'':' — API bekliyor'}</option>)}</select></label><label>Sipariş<select value={orderNo} onChange={e=>setOrderNo(e.target.value)}><option value="">Sipariş seç</option>{orders.map(o=><option key={o.OrderNo||o.id} value={o.OrderNo||o.id}>{o.OrderNo||o.id} — {o.FirstName||o.customer?.name||'Müşteri'} — {o.Status||o.status}</option>)}</select></label><button className="primary" onClick={create} disabled={busy||!orderNo}>{busy?'Bağlanıyor…':'Gönderi oluştur'}</button>{message&&<div className="message">{message}</div>}</section>
 <section className="info"><h2>Kurulum</h2><p>API kullanıcı adı, şifre ve müşteri kodları sunucu ortam değişkenlerinde tutulacak. GitHub'a gizli anahtar yazılmayacak.</p><p>Aras Kargo resmi entegrasyonunda gönderi oluşturma, barkod/etiket ve sorgulama servisleri bulunuyor. Entegrasyon hesabı Aras tarafından tanımlandığında gerçek gönderi oluşturma çağrısını bu panele bağlayacağız.</p><a href="https://www.araskargo.com.tr/kurumsal-cozumlerimiz/entegrasyon-hizmetlerimiz" target="_blank" rel="noreferrer">Aras Kargo entegrasyon bilgileri <ExternalLink size={14}/></a></section>
 <style jsx>{`body{background:#f6f4f0}.shipping-admin{max-width:1100px;margin:0 auto;padding:36px 22px 80px;color:#171717}.back{display:inline-flex;align-items:center;gap:8px;color:#555;text-decoration:none;font-size:14px}.shipping-admin header{padding:30px 0}.shipping-admin header small{display:block;margin-top:36px;font-size:11px;letter-spacing:.16em;color:#777}.shipping-admin h1{font-size:clamp(34px,5vw,58px);line-height:1;margin:12px 0}.shipping-admin header p{max-width:700px;color:#666;line-height:1.6}.provider-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.provider-grid article{background:#fff;border:1px solid #e5e1db;border-radius:18px;padding:18px;display:flex;align-items:center;gap:13px}.provider-grid article.ready{border-color:#d7e8d9}.provider-icon{width:40px;height:40px;border-radius:12px;background:#f2f0ec;display:grid;place-items:center}.provider-grid h2{font-size:16px;margin:0 0 4px}.provider-grid span{font-size:12px;color:#777}.ok{color:#318347;margin-left:auto}.warn{color:#b06b13;margin-left:auto}.shipping-card,.info{margin-top:18px;background:#fff;border:1px solid #e5e1db;border-radius:22px;padding:24px}.card-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:20px}.card-head small{font-size:10px;letter-spacing:.14em;color:#888}.card-head h2,.info h2{margin:6px 0 0;font-size:24px}.card-head button{border:1px solid #ddd;background:#fff;border-radius:10px;padding:9px 12px;display:flex;gap:7px;align-items:center}.shipping-card label{display:block;font-size:12px;color:#666;margin:14px 0}.shipping-card select{display:block;width:100%;margin-top:7px;padding:13px;border:1px solid #ddd;border-radius:10px;background:#fff;font:inherit}.primary{margin-top:10px;width:100%;border:0;border-radius:12px;padding:14px;background:#f58a1f;color:#111;font-weight:700;cursor:pointer}.primary:disabled{opacity:.5;cursor:not-allowed}.message{margin-top:14px;padding:12px;border-radius:10px;background:#f6f4f0;color:#555;font-size:13px}.info p{color:#666;line-height:1.6;font-size:14px}.info a{display:inline-flex;align-items:center;gap:6px;color:#111;font-weight:600;text-decoration:none}.info a:hover{text-decoration:underline}@media(max-width:760px){.provider-grid{grid-template-columns:1fr}.shipping-admin{padding:20px 15px 60px}.shipping-admin header{padding:20px 0}}`}</style>
 </main>
}
