import Link from 'next/link';
import {ShieldCheck,LockKeyhole,FileCheck2,MapPin,Phone,Mail} from 'lucide-react';
import {COMPANY} from '../company-info';

const content={
 contact:{title:'İletişim',intro:'ALYA HOMES ile sipariş, ürün, kargo, iade ve diğer konular hakkında aşağıdaki resmî iletişim kanallarından iletişime geçebilirsiniz.',sections:[['Müşteri Hizmetleri',`Siparişiniz, ürünlerimiz veya site kullanımıyla ilgili destek taleplerinizi ${COMPANY.email} adresine iletebilir veya ${COMPANY.phone} numaralı telefondan bize ulaşabilirsiniz.`],['Sipariş ve Kargo','Sipariş numaranızı belirterek teslimat, kargo ve sipariş süreçleriniz hakkında destek talep edebilirsiniz.'],['Kurumsal İletişim',`${COMPANY.name} şirket bilgileri aşağıda yer almaktadır.`]]},
 secure:{title:'Güvenli Alışveriş',intro:'ALYA HOMES alışveriş deneyiminde bağlantı ve ödeme güvenliğini korumaya yönelik teknik ve operasyonel kontroller uygulanır.',sections:[['Şifreli bağlantı','Site bağlantılarında HTTPS/SSL-TLS kullanılır. Tarayıcınızın adres çubuğundaki kilit simgesi bağlantının şifreli olduğunu gösterir.'],['Ödeme güvenliği','Ödeme bilgilerinin işlenmesi, kullanılan ödeme kuruluşunun güvenli ödeme altyapısı ve ilgili teknik kontroller üzerinden gerçekleştirilir. Ödeme sağlayıcısına ilişkin kesin bilgiler entegrasyon doğrulandıkça ayrıca yayımlanacaktır.'],['Hesap güvenliği','Hesap şifrenizi üçüncü kişilerle paylaşmamanızı ve ortak kullanılan cihazlarda hesabınızdan çıkış yapmanızı öneririz.']]},
 privacy:{title:'Kişisel Verilerin Korunması',intro:'Bu sayfa ALYA HOMES tarafından kişisel verilerin işlenmesine ilişkin temel bilgilendirme alanıdır.',sections:[['Veri sorumlusu',`${COMPANY.name}, ${COMPANY.address} adresinde faaliyet göstermektedir. İletişim: ${COMPANY.email} · ${COMPANY.phone}.`],['İşlenen veriler','Sipariş, teslimat, müşteri hesabı ve iletişim süreçlerinin gerektirdiği kimlik, iletişim, adres ve işlem bilgileri ilgili süreç kapsamında ve yürürlükteki mevzuata uygun olarak işlenebilir.'],['Haklarınız','Yürürlükteki kişisel verilerin korunması mevzuatı kapsamında sahip olduğunuz haklar ve başvuru yöntemleri, ilgili aydınlatma metni ve başvuru süreçlerinde açıklanır.']]},
 membership:{title:'Üyelik Sözleşmesi',intro:'ALYA HOMES üyelik hesabının oluşturulması ve kullanılması için geçerli olacak genel üyelik kuralları.',sections:[['Üyelik','Üyelik sırasında verilen bilgilerin doğru ve güncel tutulması kullanıcının sorumluluğundadır.'],['Hesap kullanımı','Hesap bilgileri kişiye özeldir. Yetkisiz kullanım şüphesinde ALYA HOMES destek kanallarından iletişime geçilmelidir.'],['Şirket bilgileri',`${COMPANY.name} · ${COMPANY.address} · ${COMPANY.email} · ${COMPANY.phone}`]]},
 cookies:{title:'Çerez Politikası',intro:'ALYA HOMES web sitesinde kullanıcı deneyimini geliştirmek, siteyi çalıştırmak ve gerekli ölçümleme faaliyetlerini yürütmek amacıyla çerez teknolojileri kullanılabilir.',sections:[['Zorunlu çerezler','Sepet, oturum, güvenlik ve temel site işlevlerinin çalışması için gerekli çerezler kullanılabilir.'],['Tercih ve analiz çerezleri','Kullanıcı tercihleri ve site kullanımının anlaşılması için kullanılan çerezler, ilgili izin ve yasal gerekliliklere göre yönetilecektir.'],['Kontrol','Tarayıcı ayarlarınızdan çerezleri engelleyebilir veya silebilirsiniz; ancak bazı site özellikleri bundan etkilenebilir.']]},
 communication:{title:'İletişim Aydınlatma Metni',intro:'İletişim kanalları üzerinden gerçekleştirilen veri işleme faaliyetleri hakkında bilgilendirme alanıdır.',sections:[['Veri sorumlusu',`${COMPANY.name} · ${COMPANY.address}`],['Amaç','Destek taleplerini yanıtlamak, müşteri iletişimini yürütmek ve talebinizle ilgili işlem yapmak amacıyla iletişim bilgileriniz kullanılabilir.'],['İletişim kanalları',`E-posta: ${COMPANY.email} · Telefon: ${COMPANY.phone}. İletişim yoluyla iletilen bilgiler ilgili talebin çözümüyle sınırlı olarak değerlendirilebilir.`]]},
 terms:{title:'Kullanım Koşulları',intro:'ALYA HOMES web sitesinin kullanımına ilişkin genel kurallar ve kullanıcı sorumlulukları.',sections:[['Site kullanımı','Site içeriği ve hizmetleri yürürlükteki mevzuata uygun şekilde kullanılmalıdır.'],['İçerik','Ürün görselleri, marka unsurları, metinler ve diğer site içerikleri ALYA HOMES veya ilgili hak sahiplerinin izni olmadan ticari amaçla kullanılamaz.'],['İşletme bilgileri',`${COMPANY.name} · ${COMPANY.address} · Vergi Dairesi: ${COMPANY.taxOffice} · Vergi No: ${COMPANY.taxNumber} · MERSİS: ${COMPANY.mersisNumber}`]]},
 commercial:{title:'Ticari İletişim Bilgilendirme Metni',intro:'ALYA HOMES tarafından gönderilebilecek kampanya, ürün ve ticari iletişim içeriklerine ilişkin bilgilendirme alanıdır.',sections:[['Ticari iletişim','Kampanya ve tanıtım iletileri yalnızca gerekli izin ve hukuki dayanaklara uygun olarak gönderilecektir.'],['Tercih yönetimi','Ticari ileti almayı tercih etmeyen kullanıcılar sunulan ret/abonelikten çıkma kanallarını kullanabilir.'],['İletişim',`Ticari iletişim süreçleriyle ilgili talepler ${COMPANY.email} adresine veya ${COMPANY.phone} numarasına iletilebilir.`]]},
 help:{title:'Yardım Merkezi',intro:'Siparişten teslimata kadar ALYA HOMES alışveriş sürecinde ihtiyaç duyabileceğiniz temel bilgiler.',sections:[['Sipariş','Ürün sayfasından ürünü sepete ekleyip sepet ve ödeme adımlarını tamamlayarak sipariş oluşturabilirsiniz.'],['Kargo ve teslimat','Sipariş sonrası kargo bilgileri ve takip numarası hesabınızdan veya sipariş bilgilendirmelerinden takip edilebilir.'],['İletişim ve destek',`Destek için ${COMPANY.email} adresine e-posta gönderebilir veya ${COMPANY.phone} numarasından ulaşabilirsiniz.`]]},
 campaigns:{title:'Kampanyalar',intro:'ALYA HOMES kampanya ve özel fırsatlarının yayımlanacağı alan.',sections:[['Aktif kampanyalar','Kampanyalar aktif oldukları tarih aralığı, ürün kapsamı ve varsa kullanım koşullarıyla birlikte burada yayımlanacaktır.'],['Kampanya koşulları','Her kampanyanın özel koşulları kampanya duyurusunda açıkça belirtilir.'],['Bilgilendirme','Kampanyaların birleştirilip birleştirilemeyeceği, stok sınırları ve diğer şartlar ilgili kampanya duyurusunda yer alacaktır.']]},
 security:{title:'Güvenlik Sertifikaları',intro:'ALYA HOMES web sitesinin bağlantı ve güvenlik altyapısına ilişkin doğrulanabilir bilgilerin yer alacağı alan.',sections:[['SSL / TLS','Site ile tarayıcı arasındaki iletişim HTTPS üzerinden şifrelenir. Kullanıcılar sertifika durumunu tarayıcı adres çubuğundan kontrol edebilir.'],['Ödeme altyapısı','Kullanılan ödeme kuruluşunun sertifikaları ve güvenlik standartları, sağlayıcı kesinleştiğinde doğrulanabilir bilgilerle bu bölüme eklenecektir.'],['Güvenlik bildirimi',`Şüpheli bir işlem veya güvenlik açığı fark ettiğinizde ${COMPANY.email} üzerinden ALYA HOMES'e bildirim yapabilirsiniz.`]]}
};

function CompanyCard(){return <div className="alya-company-card"><h2>Şirket Bilgileri</h2><p><strong>{COMPANY.name}</strong></p><p><MapPin size={16}/><span>{COMPANY.address}</span></p><p><Phone size={16}/><span>{COMPANY.phone}</span></p><p><Mail size={16}/><span>{COMPANY.email}</span></p><p><span><strong>Vergi Dairesi:</strong> {COMPANY.taxOffice} · <strong>Vergi No:</strong> {COMPANY.taxNumber}</span></p><p><span><strong>MERSİS No:</strong> {COMPANY.mersisNumber}</span></p></div>}

export default function LegalPage({type}){const data=content[type]||content.help;const showCompany=type==='contact'||type==='privacy'||type==='communication';return <main className="alya-legal-page"><div className="alya-legal-wrap"><span className="alya-legal-kicker">ALYA HOMES</span><h1>{data.title}</h1><p className="alya-legal-intro">{data.intro}</p><div className="alya-legal-meta">Resmî şirket bilgileri · {COMPANY.shortName}</div>{showCompany&&<CompanyCard/>}{type==='security'&&<div className="alya-security-grid"><div className="alya-security-card"><ShieldCheck size={22}/><strong>SSL / TLS</strong><span>Şifreli web bağlantısı</span></div><div className="alya-security-card"><LockKeyhole size={22}/><strong>Güvenli bağlantı</strong><span>HTTPS üzerinden iletişim</span></div><div className="alya-security-card"><FileCheck2 size={22}/><strong>Doğrulanabilir bilgiler</strong><span>Sertifika ve sağlayıcı bilgileri doğrulandıkça yayımlanır</span></div></div>}{data.sections.map(([title,text])=><section className="alya-legal-section" key={title}><h2>{title}</h2><p>{text}</p></section>)}<div className="alya-legal-links"><Link href="/iletisim">İletişim</Link><Link href="/yardim">Yardım</Link><Link href="/guvenli_alisveris">Güvenli Alışveriş</Link></div></div></main>}
