import Link from 'next/link';
import {ShieldCheck,LockKeyhole,FileCheck2} from 'lucide-react';

const content={
 contact:{title:'İletişim',intro:'ALYA HOMES ile sipariş, ürün, kargo, iade ve diğer konular hakkında iletişime geçebilirsiniz.',sections:[['Müşteri Hizmetleri','Siparişiniz, ürünlerimiz veya site kullanımıyla ilgili destek taleplerinizi bize iletebilirsiniz. Resmî şirket iletişim bilgileri, işletme bilgileriniz tarafımıza ulaştığında bu sayfaya eklenecektir.'],['Sipariş ve Kargo','Sipariş numaranızı belirterek teslimat ve kargo süreçleriniz hakkında destek talep edebilirsiniz.'],['Kurumsal İletişim','Ticari unvan, adres, telefon, e-posta ve diğer yasal iletişim bilgileri doğrulama sonrasında bu bölümde yayımlanacaktır.']]},
 secure:{title:'Güvenli Alışveriş',intro:'ALYA HOMES alışveriş deneyiminde bağlantı ve ödeme güvenliğini korumaya yönelik teknik ve operasyonel kontroller uygulanır.',sections:[['Şifreli bağlantı','Site bağlantılarında HTTPS/SSL-TLS kullanılır. Tarayıcınızın adres çubuğundaki kilit simgesi bağlantının şifreli olduğunu gösterir.'],['Ödeme güvenliği','Ödeme bilgilerinin işlenmesi kullanılan ödeme kuruluşunun güvenli ödeme altyapısı üzerinden gerçekleştirilir. Sağlayıcıya ilişkin kesin bilgiler entegrasyon tamamlandığında güncellenecektir.'],['Hesap güvenliği','Hesap şifrenizi üçüncü kişilerle paylaşmamanızı ve ortak kullanılan cihazlarda hesabınızdan çıkış yapmanızı öneririz.']]},
 privacy:{title:'Kişisel Verilerin Korunması',intro:'Bu sayfa ALYA HOMES tarafından kişisel verilerin işlenmesine ilişkin temel bilgilendirme alanıdır. Nihai hukuki metin şirket bilgileriniz doğrulandıktan sonra tamamlanacaktır.',sections:[['Veri sorumlusu','ALYA HOMES işletmesine ait gerçek ticari unvan ve iletişim bilgileri tarafınızdan iletildiğinde bu bölümde açıkça belirtilecektir.'],['İşlenen veriler','Sipariş, teslimat, müşteri hesabı ve iletişim süreçlerinin gerektirdiği kimlik, iletişim, adres ve işlem bilgileri ilgili süreç kapsamında işlenebilir.'],['Haklarınız','Yürürlükteki kişisel verilerin korunması mevzuatı kapsamında sahip olduğunuz haklar ve başvuru yöntemi nihai aydınlatma metninde ayrıntılı olarak açıklanacaktır.']]},
 membership:{title:'Üyelik Sözleşmesi',intro:'ALYA HOMES üyelik hesabının oluşturulması ve kullanılması için geçerli olacak sözleşme yapısı.',sections:[['Üyelik','Üyelik sırasında verilen bilgilerin doğru ve güncel tutulması kullanıcının sorumluluğundadır.'],['Hesap kullanımı','Hesap bilgileri kişiye özeldir. Yetkisiz kullanım şüphesinde ALYA HOMES destek kanallarından iletişime geçilmelidir.'],['Nihai metin','Tarafların kimliği, ticari unvan ve diğer zorunlu sözleşme bilgileri doğrulandıktan sonra nihai sözleşme metni yayımlanacaktır.']]},
 cookies:{title:'Çerez Politikası',intro:'ALYA HOMES web sitesinde kullanıcı deneyimini geliştirmek, siteyi çalıştırmak ve gerekli ölçümleme faaliyetlerini yürütmek amacıyla çerez teknolojileri kullanılabilir.',sections:[['Zorunlu çerezler','Sepet, oturum, güvenlik ve temel site işlevlerinin çalışması için gerekli çerezler kullanılabilir.'],['Tercih ve analiz çerezleri','Kullanıcı tercihleri ve site kullanımının anlaşılması için kullanılan çerezler, ilgili izin ve yasal gerekliliklere göre yönetilecektir.'],['Kontrol','Tarayıcı ayarlarınızdan çerezleri engelleyebilir veya silebilirsiniz; ancak bazı site özellikleri bundan etkilenebilir.']]},
 communication:{title:'İletişim Aydınlatma Metni',intro:'İletişim kanalları üzerinden gerçekleştirilen veri işleme faaliyetleri hakkında bilgilendirme alanıdır.',sections:[['Amaç','Destek taleplerini yanıtlamak, müşteri iletişimini yürütmek ve talebinizle ilgili işlem yapmak amacıyla iletişim bilgileriniz kullanılabilir.'],['Kapsam','E-posta, telefon, iletişim formu ve benzeri kanallardan iletilen bilgiler ilgili talebin çözümüyle sınırlı olarak değerlendirilebilir.'],['Başvuru','Resmî veri sorumlusu bilgileri doğrulandıktan sonra başvuru kanalları ve ayrıntılı yasal bilgiler bu sayfaya eklenecektir.']]},
 terms:{title:'Kullanım Koşulları',intro:'ALYA HOMES web sitesinin kullanımına ilişkin genel kurallar ve kullanıcı sorumlulukları.',sections:[['Site kullanımı','Site içeriği ve hizmetleri yürürlükteki mevzuata uygun şekilde kullanılmalıdır.'],['İçerik','Ürün görselleri, marka unsurları, metinler ve diğer site içerikleri ALYA HOMES veya ilgili hak sahiplerinin izni olmadan ticari amaçla kullanılamaz.'],['Değişiklikler','Site özellikleri ve kullanım koşulları, yasal gereklilikler veya hizmet geliştirmeleri doğrultusunda güncellenebilir.']]},
 commercial:{title:'Ticari İletişim Bilgilendirme Metni',intro:'ALYA HOMES tarafından gönderilebilecek kampanya, ürün ve ticari iletişim içeriklerine ilişkin bilgilendirme alanıdır.',sections:[['Ticari iletişim','Kampanya ve tanıtım iletileri yalnızca gerekli izin ve hukuki dayanaklara uygun olarak gönderilecektir.'],['Tercih yönetimi','Ticari ileti almayı tercih etmeyen kullanıcılar sunulan ret/abonelikten çıkma kanallarını kullanabilir.'],['Kapsam','SMS, e-posta ve benzeri iletişim kanallarına ilişkin sağlayıcı ve izin ayrıntıları entegrasyon tamamlandığında güncellenecektir.']]},
 help:{title:'Yardım Merkezi',intro:'Siparişten teslimata kadar ALYA HOMES alışveriş sürecinde ihtiyaç duyabileceğiniz temel bilgiler.',sections:[['Sipariş','Ürün sayfasından ürünü sepete ekleyip sepet ve ödeme adımlarını tamamlayarak sipariş oluşturabilirsiniz.'],['Kargo ve teslimat','Sipariş sonrası kargo bilgileri ve takip numarası hesabınızdan veya sipariş bilgilendirmelerinden takip edilebilir.'],['İade ve değişim','İade/değişim koşulları, süreleri ve başvuru yöntemi şirket operasyon bilgileriniz doğrulandığında ayrıntılı olarak yayımlanacaktır.']]},
 campaigns:{title:'Kampanyalar',intro:'ALYA HOMES kampanya ve özel fırsatlarının yayımlanacağı alan.',sections:[['Aktif kampanyalar','Kampanyalar aktif oldukları tarih aralığı, ürün kapsamı ve varsa kullanım koşullarıyla birlikte burada yayımlanacaktır.'],['Kampanya koşulları','Her kampanyanın özel koşulları kampanya duyurusunda açıkça belirtilir.'],['Bilgilendirme','Kampanyaların birleştirilip birleştirilemeyeceği, stok sınırları ve diğer şartlar ilgili kampanya duyurusunda yer alacaktır.']]},
 security:{title:'Güvenlik Sertifikaları',intro:'ALYA HOMES web sitesinin bağlantı ve güvenlik altyapısına ilişkin doğrulanabilir bilgilerin yer alacağı alan.',sections:[['SSL / TLS','Site ile tarayıcı arasındaki iletişim HTTPS üzerinden şifrelenir. Kullanıcılar sertifika durumunu tarayıcı adres çubuğundan kontrol edebilir.'],['Ödeme altyapısı','Kullanılan ödeme kuruluşunun sertifikaları ve güvenlik standartları, sağlayıcı kesinleştiğinde doğrulanabilir bilgilerle bu bölüme eklenecektir.'],['Güvenlik bildirimi','Şüpheli bir işlem veya güvenlik açığı fark ettiğinizde ALYA HOMES iletişim kanallarından bildirim yapabilirsiniz.']]}
};

export default function LegalPage({type}){const data=content[type]||content.help;return <main className="alya-legal-page"><div className="alya-legal-wrap"><span className="alya-legal-kicker">ALYA HOMES</span><h1>{data.title}</h1><p className="alya-legal-intro">{data.intro}</p><div className="alya-legal-meta">Bilgilendirme sayfası · Nihai şirket bilgileri ve hukuki metinler doğrulama sonrası güncellenecektir.</div>{type==='security'&&<div className="alya-security-grid"><div className="alya-security-card"><ShieldCheck size={22}/><strong>SSL / TLS</strong><span>Şifreli web bağlantısı</span></div><div className="alya-security-card"><LockKeyhole size={22}/><strong>Güvenli bağlantı</strong><span>HTTPS üzerinden iletişim</span></div><div className="alya-security-card"><FileCheck2 size={22}/><strong>Doğrulanabilir bilgiler</strong><span>Sertifika ve sağlayıcı bilgileri doğrulama sonrası eklenecek</span></div></div>}{data.sections.map(([title,text])=><section className="alya-legal-section" key={title}><h2>{title}</h2><p>{text}</p></section>)}<div className="alya-legal-note">Bu sayfa altyapı ve içerik iskeleti olarak hazırlanmıştır. Resmî şirket bilgilerinizi gönderdiğinizde ilgili alanları ALYA HOMES adına doğru bilgilerle tamamlayacağız.</div><div className="alya-legal-links"><Link href="/iletisim">İletişim</Link><Link href="/yardim">Yardım</Link><Link href="/guvenli_alisveris">Güvenli Alışveriş</Link></div></div></main>}
