"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {ArrowRight,Package,UserRound,MapPin,LogOut,ChevronRight} from "lucide-react";
import {useStore} from "../store";
const money=n=>new Intl.NumberFormat("tr-TR",{style:"currency",currency:"TRY",maximumFractionDigits:0}).format(n);
export default function Account(){const {customer,orders,saveCustomer,clearCustomer}=useStore();const [sqlCustomer,setSqlCustomer]=useState(null),[sqlOrders,setSqlOrders]=useState([]),[editing,setEditing]=useState(false),[saving,setSaving]=useState(false),[form,setForm]=useState({});
useEffect(()=>{if(!customer?.email)return;let gone=false;Promise.all([fetch(`/api/customers?email=${encodeURIComponent(customer.email)}`,{cache:"no-store"}).then(r=>r.json()),fetch(`/api/orders?email=${encodeURIComponent(customer.email)}`,{cache:"no-store"}).then(r=>r.json())]).then(([c,o])=>{if(gone)return;if(c.customer){setSqlCustomer(c.customer);setForm({firstName:c.customer.FirstName||customer.name?.split(" ")[0]||"",lastName:c.customer.LastName||"",phone:c.customer.Phone||customer.phone||"",addressLine:c.customer.AddressLine||"",city:c.customer.City||"",district:c.customer.District||"",postalCode:c.customer.PostalCode||""})}if(Array.isArray(o.orders))setSqlOrders(o.orders)}).catch(()=>{});return()=>{gone=true}},[customer?.email]);
if(!customer)return <main className="account-page"><div className="account-hero"><small>ALYA HOMES</small><h1>Müşteri hesabı</h1><p>Siparişlerinizi ve teslimat bilgilerinizi tek yerden yönetin.</p></div><section className="account-login"><UserRound size={28}/><h2>Hesabınıza giriş yapın</h2><p>Hesap bilgilerinizi oluşturduğunuzda siparişlerinizi bu cihazda takip edebilirsiniz.</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);saveCustomer({name:f.get("name"),email:f.get("email"),phone:f.get("phone"),address:""})}}><input name="name" required placeholder="Ad soyad"/><input name="email" type="email" required placeholder="E-posta"/><input name="phone" placeholder="Telefon"/><button className="button dark" type="submit">Hesap oluştur <ArrowRight size={16}/></button></form></section></main>;
const displayOrders=sqlOrders.length?sqlOrders:orders;const displayName=[sqlCustomer?.FirstName,sqlCustomer?.LastName].filter(Boolean).join(" ")||customer.name;const address=[sqlCustomer?.AddressLine,sqlCustomer?.District,sqlCustomer?.City,sqlCustomer?.PostalCode].filter(Boolean).join(", ");
const save=async e=>{e.preventDefault();setSaving(true);try{const r=await fetch("/api/customers",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:sqlCustomer?.Id, ...form})});if(!r.ok)throw new Error();saveCustomer({...customer,name:[form.firstName,form.lastName].filter(Boolean).join(" "),phone:form.phone,address:form.addressLine});setEditing(false);setSqlCustomer(x=>x?{...x,...form,FirstName:form.firstName,LastName:form.lastName,Phone:form.phone,AddressLine:form.addressLine,City:form.city,District:form.district,PostalCode:form.postalCode}:x)}catch{alert("Adres bilgileri kaydedilemedi.")}finally{setSaving(false)}};
return <main className="account-page"><div className="account-hero"><small>ALYA HOMES / HESABIM</small><h1>Merhaba, {displayName}</h1><p>{customer.email}</p></div><div className="account-grid"><section className="account-card"><div className="account-card-title"><Package/><h2>Siparişlerim</h2></div>{!displayOrders.length?<div className="account-empty">Henüz siparişiniz yok.<Link href="/collections/all">Ürünleri keşfet <ArrowRight size={15}/></Link></div>:displayOrders.map(o=><Link href={`/account/orders/${encodeURIComponent(o.OrderNo||o.id)}`} className="order-row" key={o.OrderNo||o.id}><div><strong>{o.OrderNo||o.id}</strong><span>{new Date(o.CreatedAt||o.createdAt).toLocaleDateString("tr-TR")}</span></div><div><span>{o.Status||o.status}</span><strong>{money(o.Total??o.total)}</strong><ChevronRight size={17}/></div></Link>)}</section><aside><div className="account-card"><div className="account-card-title"><MapPin/><h2>Adres bilgileri</h2></div>{editing?<form className="address-form" onSubmit={save}><input value={form.firstName} onChange={e=>setForm({...form,firstName:e.target.value})} placeholder="Ad"/><input value={form.lastName} onChange={e=>setForm({...form,lastName:e.target.value})} placeholder="Soyad"/><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="Telefon"/><textarea value={form.addressLine} onChange={e=>setForm({...form,addressLine:e.target.value})} placeholder="Adres" rows="3"/><div className="address-two"><input value={form.district} onChange={e=>setForm({...form,district:e.target.value})} placeholder="İlçe"/><input value={form.city} onChange={e=>setForm({...form,city:e.target.value})} placeholder="İl"/></div><input value={form.postalCode} onChange={e=>setForm({...form,postalCode:e.target.value})} placeholder="Posta kodu"/><div className="form-actions"><button type="button" className="text-button" onClick={()=>setEditing(false)}>Vazgeç</button><button className="button dark" disabled={saving}>{saving?"Kaydediliyor…":"Kaydet"}</button></div></form>:<><p>{address||"Adres henüz kaydedilmedi."}</p><button className="text-button" onClick={()=>setEditing(true)}>Adresi düzenle</button></>}</div><button className="logout" onClick={clearCustomer}><LogOut size={16}/> Çıkış yap</button></aside></div></main>}