import './globals.css';
import './alyahomes-reference.css';
import './home.css';
import './brand.css';
import './alya-experience.css';
import './home-polish.css';
import './header-polish.css';
import './collection-polish.css';
import './product-detail-polish.css';
import './cart-polish.css';
import './wishlist-polish.css';
import './account-polish.css';
import './checkout-polish.css';
import './order-success-polish.css';
import './order-detail-polish.css';
import './legal-page.css';
import './footer-polish.css';
import './design-system-polish.css';
import { StoreProvider } from './store';
import SiteHeader from './components/SiteHeader';
import SiteFooter from './components/SiteFooter';
import ScrollHeaderController from './components/ScrollHeaderController';
export const metadata={title:'ALYA HOMES | Ev Yaşam Ürünleri',description:'ALYA HOMES ürün koleksiyonu'};
export default function RootLayout({children}){return <html lang="tr"><body><StoreProvider><SiteHeader/><ScrollHeaderController/>{children}<SiteFooter/></StoreProvider></body></html>}
