import './globals.css';
import './alyahomes-reference.css';
import './home.css';
import './brand.css';
import './alya-experience.css';
import './home-polish.css';
import './header-polish.css';
import './collection-polish.css';
import './product-detail-polish.css';
import './product-gallery-final.css';
import './product-image-scale.css';
import './cart-polish.css';
import './wishlist-polish.css';
import './account-polish.css';
import './checkout-polish.css';
import './order-success-polish.css';
import './order-detail-polish.css';
import './legal-page.css';
import './footer-polish.css';
import './design-system-polish.css';
import './retail-redesign.css';
import { StoreProvider } from './store';
import SiteHeader from './components/SiteHeader';
import SiteFooter from './components/SiteFooter';
import ScrollHeaderController from './components/ScrollHeaderController';
import {isCatalogMode} from './site-config';
import {I18nProvider} from './i18n';
export const metadata={title:isCatalogMode?'ALYA HOMES | Ev Yaşam Ürünleri':'ALYA HOMES Shop | Online Mağaza',description:isCatalogMode?'ALYA HOMES ürün koleksiyonu':'ALYA HOMES online mağazası'};
export default function RootLayout({children}){return <html lang="tr"><body><StoreProvider><I18nProvider><SiteHeader/><ScrollHeaderController/>{children}<SiteFooter/></I18nProvider></StoreProvider></body></html>}
