"use client";
import {useMemo,useState} from 'react'; import {Search,Heart,UserRound,ShoppingBag,Menu,X,ChevronDown,ArrowRight,Plus,Minus,MapPin,ShieldCheck,Truck,RotateCcw,Sparkles} from 'lucide-react'; import Link from 'next/link'; import {products,categories} from './products'; import {useStore} from './store';
const money=n=>n==null?'Fiyat için iletişime geçin':new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY',maximumFractionDigits:0}).format(n);
function ProductCard({product,onAdd}){const {toggleWishlist,isWishlisted}=useStore(); return <article className="product"><Link href={`/products/${product.slug}`}><div className="product-image"><span>ALYA HOMES</span><button aria-label="Favorilere ekle" className={isWishlisted(product.slug)?'wish-active':''} onClick={e=>{e.preventDefault();e.stopPropagation();toggleWishlist(product)}}><Heart size={19} fill={isWishlisted(product.slug)?'currentColor':'none'}/></button><img src={product.image} alt={product.name}/></div><div className="product-meta"><span className="code">{product.code}</span><h3>{product.name}</h3><p>{money(product.price)}</p></div></Link><button className="add" onClick={()=>onAdd(product)}>{product.price==null?'Fiyat iste':'Sepete ekle'}</button></article>}
export default function Home(){const [searchOpen,setSearchOpen]=useState(false),[menuOpen,setMenuOpen]=useState(false),[cartOpen,setCartOpen]=useState(false),[locationOpen,setLocationOpen]=useState(false),[query,setQuery]=useState(''),[newsletterEmail,setNewsletterEmail]=useState(''),[newsletterSent,setNewsletterSent]=useState(false); const {cart,addToCart,changeQty,count,total,wishlistCount}=useStore(); const filtered=useMemo(()=>products.filter(p=>(p.name+' '+p.code+' '+p.category).toLowerCase().includes(query.toLowerCase())).slice(0,8),[query]);
const dryingProduct=products.find(p=>p.code==='AHDRY1409')||products[8];
const dryingCategoryImage=products.find(p=>p.category==='Kurutmalıklar')?.image;
const boardCategoryImage=products.find(p=>p.category==='Ütü Masaları')?.image;
const newProducts=products.slice(5,10);
return <><div className="announcement">1.000 TL ve üzeri siparişlerde ücretsiz kargo</div><header><div className="utility"><div className="utility-links"><span>3 yıl garanti</span><span>30 gün içinde kolay iade</span><span>Güvenli ödeme</span><button onClick={()=>setLocationOpen(true)}><MapPin size={12}/> Türkiye / TRY</button></div></div><div className="main-header"><button className="mobile-menu" onClick={()=>setMenuOpen(true)}><Menu/></button><Link href="/" className="brand-logo"><img src="/alya-homes-logo.png" alt="ALYA HOMES"/></Link><nav><Link href="/collections/all">Tüm Ürünler</Link><Link href="/collections/kurutmalıklar">Kurutmalıklar <ChevronDown size={13}/></Link><Link href="/collections/ütü%20masaları">Ütü Masaları <ChevronDown size={13}/></Link></nav><div className="actions"><button onClick={()=>setSearchOpen(true)} aria-label="Ara"><Search size={21}/></button><Link href="/account" aria-label="Hesabım" className="icon-link"><UserRound size={21}/></Link><Link href="/wishlist" aria-label="Favoriler" className="icon-link"><Heart size={21}/><b>{wishlistCount}</b></Link><button className="cart" onClick={()=>setCartOpen(true)} aria-label="Sepet"><ShoppingBag size={21}/><b>{count}</b></button></div></div></header>
{menuOpen&&<div className="mobile-panel"><div className="panel-top"><img src="/alya-homes-logo.png" alt="ALYA HOMES"/><button onClick={()=>setMenuOpen(false)}><X/></button></div><Link href="/" onClick={()=>setMenuOpen(false)}>Ana Sayfa <ArrowRight size={16}/></Link>{categories.map(c=><Link key={c} href={`/collections/${encodeURIComponent(c.toLowerCase())}`} onClick={()=>setMenuOpen(false)}>{c}<ArrowRight size={16}/></Link>)}<Link href="/account" onClick={()=>setMenuOpen(false)}>Hesabım <ArrowRight size={16}/></Link><Link href="/wishlist" onClick={()=>setMenuOpen(false)}>Favoriler <ArrowRight size={16}/></Link><Link href="/cart" onClick={()=>setMenuOpen(false)}>Sepet <ArrowRight size={16}/></Link></div>}
{locationOpen&&<div className="modal-backdrop" onClick={()=>setLocationOpen(false)}><div className="location-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setLocationOpen(false)}><X/></button><MapPin size={25}/><h2>Alışveriş konumunuz</h2><p>Sipariş ve para birimi bilgileri için teslimat konumunuzu seçin.</p><select defaultValue="TR"><option value="TR">Türkiye — TRY ₺</option><option disabled>Avrupa Birliği — EUR €</option></select><button className="modal-confirm" onClick={()=>setLocationOpen(false)}>Devam et</button></div></div>}
{searchOpen&&<div className="search-overlay" onClick={()=>setSearchOpen(false)}><div className="search-box" onClick={e=>e.stopPropagation()}><button className="search-close" onClick={()=>setSearchOpen(false)}><X/></button><label>Ne arıyorsunuz?</label><div className="search-input"><Search size={21}/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ürün kodu, ürün veya kategori ara"/></div>{query&&<div className="search-results">{filtered.length?filtered.map(p=><Link key={p.slug} href={`/products/${p.slug}`} onClick={()=>setSearchOpen(false)}><span>{p.name}<small>{p.code}</small></span><strong>{money(p.price)}</strong></Link>):<p>Sonuç bulunamadı.</p>}</div>}</div></div>}
{cartOpen&&<div className="drawer-backdrop" onClick={()=>setCartOpen(false)}><aside className="cart-drawer" onClick={e=>e.stopPropagation()}><div className="drawer-head"><h2>Sepet</h2><button onClick={()=>setCartOpen(false)}><X/></button></div>{!cart.length?<div className="empty-cart"><ShoppingBag size={40}/><p>Sepetiniz henüz boş.</p><Link href="/collections/all" onClick={()=>setCartOpen(false)}>Ürünleri keşfet <ArrowRight size={16}/></Link></div>:<><div className="cart-items">{cart.map(item=><div className="cart-item" key={item.slug}><img src={item.image} alt=""/><div><Link href={`/products/${item.slug}`}>{item.name}</Link><strong>{money(item.price)}</strong><div className="qty"><button onClick={()=>changeQty(item.slug,-1)}><Minus size={13}/></button><span>{item.qty}</span><button onClick={()=>changeQty(item.slug,1)}><Plus size={13}/></button></div></div></div>)}</div><div className="drawer-total"><span>Toplam</span><strong>{money(total)}</strong></div><Link className="checkout" href="/cart" onClick={()=>setCartOpen(false)}>Sepete git <ArrowRight size={17}/></Link></>}</aside></div>}
<main><section className="hero"><div className="hero-copy"><p>ALYA HOMES / KOLEKSİYON</p><h1>Eviniz için<br/>tasarlanan<br/><b>akıllı çözümler.</b></h1><Link href="/collections/all" className="button">Koleksiyonu keşfet <ArrowRight size={18}/></Link></div></section>
<section className="section products-section"><div className="section-heading"><div><small>ALYA HOMES</small><h2>Öne çıkan ürünler</h2></div><Link href="/collections/all">Tümünü gör <ArrowRight size={17}/></Link></div><div className="products">{products.slice(0,5).map(p=><ProductCard key={p.slug} product={p} onAdd={p=>{if(addToCart(p))setCartOpen(true);else window.location.href=`/products/${p.slug}`}}/>)}</div></section>
<section className="new-arrivals section"><div className="section-heading"><div><small>YENİ SEÇİMLER</small><h2>Günlük hayat için tasarlandı</h2></div><Link href="/collections/all">Tüm ürünleri incele <ArrowRight size={17}/></Link></div><div className="products">{newProducts.map(p=><ProductCard key={p.slug} product={p} onAdd={p=>{if(addToCart(p))setCartOpen(true);else window.location.href=`/products/${p.slug}`}}/>)}</div></section>
<section className="feature"><div className="feature-image"><img src={dryingProduct.image} alt={dryingProduct.name}/></div><div className="feature-copy"><small>KURUTMALIK KOLEKSİYONU</small><h2>Alüminyum ve paslanmaz çelik.</h2><p>İç ve dış mekân kullanımına uygun, uzun ömürlü ve işlevsel çözümler. Katalogdaki modelleri tek tek inceleyin.</p><Link href="/collections/kurutmalıklar" className="text-link">Kurutmalıkları keşfet <ArrowRight size={17}/></Link></div></section>
<section className="section categories"><div className="section-heading"><div><small>KOLEKSİYONLAR</small><h2>ALYA HOMES ürünleri</h2></div></div><div className="category-grid"><Link href="/collections/kurutmalıklar" className="category"><div className="category-image"><img src={dryingCategoryImage} alt="Kurutmalıklar"/></div><h3>Kurutmalıklar</h3><p>18 farklı model</p></Link><Link href="/collections/ütü%20masaları" className="category"><div className="category-image"><img src={boardCategoryImage} alt="Ütü masaları"/></div><h3>Ütü Masaları</h3><p>8 farklı model</p></Link></div></section>
<section className="design-story"><div className="design-story-intro"><small>ALYA HOMES TASARIM FELSEFESİ</small><h2>Az yer kaplar.<br/>Çok iş görür.</h2><p>Ürünlerimizi yalnızca güzel görünmesi için değil, evinizde gerçekten işe yaraması için tasarlıyoruz.</p></div><div className="story-grid"><div><ShieldCheck size={24}/><h3>Dayanıklı malzeme</h3><p>Alüminyum, paslanmaz ve çelik seçenekleriyle uzun ömürlü kullanım.</p></div><div><Sparkles size={24}/><h3>Sade tasarım</h3><p>Gereksiz detaylardan arındırılmış, işlevi öne çıkaran çizgiler.</p></div><div><RotateCcw size={24}/><h3>Kolay kullanım</h3><p>Katlanabilir ve pratik çözümlerle günlük işleri daha kolay hale getirir.</p></div></div></section>
<section className="quotes"><p>“Fonksiyonel ürünler, sade tasarım ve uzun ömürlü kullanım.”</p><span>ALYA HOMES</span></section>
<section className="benefits"><div><Truck size={22}/><strong>Ücretsiz kargo</strong><span>1.000 TL üzeri siparişlerde</span></div><div><ShieldCheck size={22}/><strong>Güvenli alışveriş</strong><span>Güvenli ödeme altyapısı</span></div><div><Sparkles size={22}/><strong>3 yıl garanti</strong><span>Ürünlerimiz garanti kapsamında</span></div><div><RotateCcw size={22}/><strong>Kolay iade</strong><span>30 gün içinde iade</span></div></section>
<section className="newsletter"><small>ALYA HOMES BÜLTENİ</small><h2>Yeni ürünlerden haberdar olun.</h2><p>Kampanyalar ve yeni ürünler için e-posta listemize katılın.</p>{newsletterSent?<div className="newsletter-success">Teşekkürler. E-posta adresiniz listeye eklendi.</div>:<form className="signup" onSubmit={e=>{e.preventDefault();if(newsletterEmail.trim())setNewsletterSent(true)}}><input type="email" required value={newsletterEmail} onChange={e=>setNewsletterEmail(e.target.value)} placeholder="E-posta adresiniz"/><button>Kayıt ol</button></form>}</section>
</main><footer><div className="footer-brand"><img src="/alya-homes-logo.png" alt="ALYA HOMES"/></div><div className="footer-grid"><div><h4>Müşteri Hizmetleri</h4><a href="mailto:info@alyahomes.com">İletişim</a><a href="/cart">Kargo ve sipariş</a><a href="/account">Hesabım</a><a href="/wishlist">Favoriler</a><a href="/account">Garanti</a></div><div><h4>Koleksiyonlar</h4><Link href="/collections/kurutmalıklar">Kurutmalıklar</Link><Link href="/collections/ütü%20masaları">Ütü Masaları</Link><Link href="/collections/all">Tüm ürünler</Link></div><div><h4>ALYA HOMES</h4><a href="mailto:info@alyahomes.com">Hakkımızda</a><a href="mailto:info@alyahomes.com">İletişim</a><a href="mailto:info@alyahomes.com">İş ortaklığı</a></div><div><h4>Yardım</h4><Link href="/account">Hesabım</Link><Link href="/wishlist">Favoriler</Link><Link href="/cart">Sepet</Link><a href="mailto:info@alyahomes.com">Destek</a></div></div><div className="payment-row"><span>VISA</span><span>Mastercard</span><span>AMEX</span><span>iyzico</span></div><div className="copyright">© 2026 ALYA HOMES. Tüm hakları saklıdır.</div></footer></>}
