const p=(slug,name,code,category,image,description,specs={})=>({slug,name,code,category,image:`/products/${image}`,price:null,description,specs});
export const products=[
 p('ahdry1401-wings-matt','WINGS MATT','AHDHY1401','Kurutmalıklar','product-5.jpg','Alüminyum ve paslanmaz yapıda, iç ve dış mekân kullanımına uygun çamaşır kurutmalık.',{kurutma:'18 m',ölçü:'200 × 55 cm',yükseklik:'118 cm',ağırlık:'1,82 kg',koli:'8 adet'}),
 p('ahdry1402-butterfly-matt','BUTTERFLY MATT','AHDHY1402','Kurutmalıklar','product-6.jpg','Katlanabilir kelebek formunda alüminyum ve paslanmaz kurutmalık.',{kurutma:'16 m',ölçü:'142 × 55 cm',yükseklik:'103 cm',ağırlık:'2,09 kg',koli:'8 adet'}),
 p('ahdry1403-basic-matt','BASIC MATT','AHDHY1403','Kurutmalıklar','product-7.jpg','Kompakt, katlanabilir ve alüminyum/paslanmaz gövdeli kurutmalık.',{kurutma:'12 m',ölçü:'104 × 50 cm',yükseklik:'92 cm',ağırlık:'1,44 kg',koli:'12 adet'}),
 p('ahdry1404-small-balcony-matt','SMALL BALCONY MATT','AHDHY1404','Kurutmalıklar','product-9.jpg','Balkon kullanımına yönelik ayarlanabilir bağlantılı kurutmalık.',{kurutma:'7 m',ölçü:'65 × 40 cm',ayar:'3–13 cm',ağırlık:'0,61 kg',koli:'10 adet'}),
 p('ahdry1405-medium-balcony-matt','MEDIUM BALCONY MATT','AHDHY1405','Kurutmalıklar','product-10.jpg','Balkon için orta ölçülü ayarlanabilir alüminyum/paslanmaz kurutmalık.',{kurutma:'9 m',ölçü:'78 × 40 cm',ayar:'3–13 cm',ağırlık:'0,65 kg',koli:'10 adet'}),
 p('ahdry1406-large-balcony-matt','LARGE BALCONY MATT','AHDHY1406','Kurutmalıklar','product-11.jpg','Balkon için geniş yüzeyli ayarlanabilir kurutmalık.',{kurutma:'11 m',ölçü:'95 × 40 cm',ayar:'3–13 cm',ağırlık:'0,83 kg',koli:'10 adet'}),
 p('ahdry1407-double-fly-matt','DOUBLE FLY MATT','AHDHY1407','Kurutmalıklar','product-13.jpg','Çift kanatlı, yüksek kurutma kapasitesine sahip katlanabilir model.',{kurutma:'21 m',ölçü:'142 cm',yükseklik:'103 cm',ağırlık:'2,23 kg',koli:'6 adet'}),
 p('ahdry1408-basic-butterfly-matt','BASIC BUTTERFLY MATT','AHDHY1408','Kurutmalıklar','product-14.jpg','Kelebek formunda temel model, alüminyum ve paslanmaz gövde.',{kurutma:'14 m',ölçü:'142 cm',yükseklik:'103 cm',ağırlık:'1,64 kg',koli:'10 adet'}),
 p('ahdry1409-side-wing-matt','SIDE WING MATT','AHDHY1409','Kurutmalıklar','product-15.jpg','Yan kanatlı katlanabilir kurutmalık.',{kurutma:'18 m',ölçü:'104 × 50 cm',yükseklik:'92 cm',ağırlık:'1,89 kg',koli:'8 adet'}),
 p('ahdry1451-wings-raw','WINGS RAW','AHDHY1451','Kurutmalıklar','product-16.jpg','Alüminyum ve paslanmaz gövdeli RAW serisi kanatlı kurutmalık.',{kurutma:'18 m',ölçü:'200 × 55 cm',yükseklik:'118 cm',ağırlık:'1,84 kg',koli:'8 adet'}),
 p('ahdry1452-butterfly-raw','BUTTERFLY RAW','AHDHY1452','Kurutmalıklar','product-17.jpg','RAW serisi kelebek formunda katlanabilir kurutmalık.',{kurutma:'16 m',ölçü:'142 × 55 cm',yükseklik:'103 cm',ağırlık:'1,94 kg',koli:'8 adet'}),
 p('ahdry1453-basic-raw','BASIC RAW','AHDHY1453','Kurutmalıklar','product-18.jpg','RAW serisi temel katlanabilir kurutmalık.',{kurutma:'12 m',ölçü:'104 × 50 cm',yükseklik:'92 cm',ağırlık:'1,22 kg',koli:'12 adet'}),
 p('ahdry1454-small-balcony-raw','SMALL BALCONY RAW','AHDHY1454','Kurutmalıklar','product-19.jpg','RAW serisi balkon tipi kurutmalık.',{kurutma:'7 m',ölçü:'65 × 40 cm',ayar:'3–13 cm',ağırlık:'0,74 kg',koli:'10 adet'}),
 p('ahdry1455-medium-balcony-raw','MEDIUM BALCONY RAW','AHDHY1455','Kurutmalıklar','product-20.jpg','RAW serisi orta balkon tipi kurutmalık.',{kurutma:'9 m',ölçü:'78 × 40 cm',ayar:'3–13 cm',ağırlık:'0,63 kg',koli:'10 adet'}),
 p('ahdry1456-large-balcony-raw','LARGE BALCONY RAW','AHDHY1456','Kurutmalıklar','product-21.jpg','RAW serisi geniş balkon tipi kurutmalık.',{kurutma:'11 m',ölçü:'95 × 40 cm',ayar:'3–13 cm',ağırlık:'0,60 kg',koli:'10 adet'}),
 p('ahdry1457-double-fly-raw','DOUBLE FLY RAW','AHDHY1457','Kurutmalıklar','product-22.jpg','RAW serisi çift kanatlı kurutmalık.',{kurutma:'21 m',ölçü:'142 cm',yükseklik:'103 cm',ağırlık:'2,25 kg',koli:'6 adet'}),
 p('ahdry1458-basic-butterfly-raw','BASIC BUTTERFLY RAW','AHDHY1458','Kurutmalıklar','product-23.jpg','RAW serisi temel kelebek model.',{kurutma:'12 m',ölçü:'142 cm',yükseklik:'103 cm',ağırlık:'1,65 kg',koli:'10 adet'}),
 p('ahdry1459-side-wing-raw','SIDE WING RAW','AHDHY1459','Kurutmalıklar','product-24.jpg','RAW serisi yan kanatlı katlanabilir kurutmalık.',{kurutma:'18 m',ölçü:'104 × 50 cm',yükseklik:'92 cm',ağırlık:'1,90 kg',koli:'8 adet'}),
 p('ahbrd1301-proboard-aluminium','PROBOARD ALUMINIUM','AHBRD1301','Ütü Masaları','product-26.jpg','45 × 120 cm ütüleme alanına sahip, alüminyum monoblok tablalı ütü masası.',{ütüleme:'45 × 120 cm',yükseklik:'68–95 cm',ağırlık:'5,50 kg',malzeme:'Alüminyum',özellik:'Buhar geçirgenliği yüksek nano keçe; Teflon kumaş'}),
 p('ahbrd1351-easyboard-aluminium','EASYBOARD ALUMINIUM','AHBRD1351','Ütü Masaları','product-28.jpg','Kompakt alüminyum monoblok tablalı ütü masası.',{ütüleme:'45 × 120 cm',yükseklik:'70–90 cm',ağırlık:'3,34 kg',malzeme:'Alüminyum',özellik:'Teflon kumaş; yüksek buhar geçirgenliği'}),
 p('ahbrd1501-proboard-hybrid','PROBOARD HYBRID','AHBRD1501','Ütü Masaları','product-30.jpg','Alüminyum tabla ve çelik ayaklı PROBOARD HYBRID.',{ütüleme:'45 × 120 cm',yükseklik:'68–95 cm',ağırlık:'6,40 kg',malzeme:'Alüminyum tabla + çelik ayak',özellik:'Buhar kazanlı ütüler için geniş park alanı'}),
 p('ahbrd1553-easyboard-hybrid','EASYBOARD HYBRID','AHBRD1553','Ütü Masaları','product-32.jpg','Alüminyum tabla ve çelik ayaklı EASYBOARD HYBRID.',{ütüleme:'45 × 120 cm',yükseklik:'70–90 cm',ağırlık:'5,20 kg',malzeme:'Alüminyum tabla + çelik ayak',özellik:'Ayarlanabilir yükseklik'}),
 p('ahbrd1601-proboard-steel','PROBOARD STEEL','AHBRD1601','Ütü Masaları','product-35.jpg','Monoblok çelik tablalı ve çelik ayaklı PROBOARD STEEL.',{ütüleme:'45 × 120 cm',yükseklik:'68–95 cm',ağırlık:'8,30 kg',malzeme:'Çelik',özellik:'Elektrostatik boyalı çelik; buhar kazanlı ütüler için geniş park alanı'}),
 p('ahbrd1605-foldable-steel','FOLDABLE STEEL','AHBRD1605','Ütü Masaları','product-37.jpg','Katlanabilir başlıklı çelik ütü masası.',{ütüleme:'45 × 120 cm',yükseklik:'68–95 cm',ağırlık:'8 kg',malzeme:'Çelik',özellik:'Katlanabilir başlık'}),
 p('ahbrd1609-slide-steel','SLIDE STEEL','AHBRD1609','Ütü Masaları','product-39.jpg','Çelik ayaklı, kayar/katlanır başlıklı ütü masası.',{ütüleme:'45 × 120 cm',yükseklik:'68–95 cm',ağırlık:'8,20 kg',malzeme:'Çelik',özellik:'Yüksek buhar geçirgenliği'}),
 p('ahbrd1653-easyboard-steel','EASYBOARD STEEL','AHBRD1653','Ütü Masaları','product-41.jpg','Çelik tablalı ve çelik ayaklı EASYBOARD STEEL.',{ütüleme:'45 × 120 cm',yükseklik:'70–90 cm',ağırlık:'7,10 kg',malzeme:'Çelik',özellik:'Ayarlanabilir yükseklik'})
];

export const categories=['Tüm Ürünler','Kurutmalıklar','Ütü Masaları'];
export const getProduct=slug=>products.find(p=>p.slug===slug);
