"use client";
import Link from 'next/link';
import {ArrowLeft, ArrowRight, LockKeyhole} from 'lucide-react';
import {useRouter} from "next/navigation";
import {useState} from "react";
import {useStore} from '../store';
const money=n=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY',maximumFractionDigits:0}).format(n);
export default function Checkout(){const {cart,total,createOrder}=useStore(); const router=useRouter(); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); if(!cart.length)return <main className="checkout-page"><div className="checkout-head"><small>ALYA HOMES</small><h1>Ödeme</h1></div><div className="checkout-empty"><h2>Ödeme için sepetinizde ürün olmalı.</h2><Link href="/collections/all" className="button dark">Ürünlere git <ArrowRight size={17}/></Link></div></main>;
return <main className="checkout-page"><div className="checkout-head"><small>ALYA HOMES</small><h1>Siparişi tamamla</h1></div><div className="checkout-layout"><form className="checkout-form" onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);setError("");const f=new FormData(e.currentTarget);const order=await createOrder({name:f.get("name"),email:f.get("email"),phone:f.get("phone"),address:f.get("address"),city:f.get("city"),district:f.get("district"),postalCode:f.get("postalCode"),payment:f.get("payment")});if(order?.error){setError(order.error);setBusy(false);return}router.push(`/order-success?order=${encodeURIComponent(order.id)}`)}}><div className="checkout-step"><span>01</span><div><h2>İletişim bilgileri</h2><input name="name" required placeholder="Ad soyad"/><input name="email" required type="email" placeholder="E-posta"/><input name="phone" placeholder="Telefon"/></div></div><div className="checkout-step"><span>02</span><div><h2>Teslimat adresi</h2><input name="address" required placeholder="Adres"/><div className="two"><input name="city" required placeholder="İl"/><input name="district" required placeholder="İlçe"/></div><input name="postalCode" placeholder="Posta kodu"/></div></div><div className="checkout-step"><span>03</span><div><h2>Ödeme yöntemi</h2><label className="pay-option"><input type="radio" name="payment" value="Kart" defaultChecked/> Kredi / banka kartı</label><label className="pay-option"><input type="radio" name="payment" value="Havale/EFT"/> Havale / EFT</label><div className="secure"><LockKeyhole size={16}/> Güvenli ödeme altyapısı</div></div></div><button className="place-order" type="submit" disabled={busy}>{busy?"Sipariş oluşturuluyor…":"Siparişi oluştur"} {!busy&&<ArrowRight size={17}/>}</button>{error&&<div className="checkout-error" role="alert">{error}</div>}</form><aside className="checkout-summary"><h2>Sipariş özeti</h2>{cart.map(i=><div className="checkout-line" key={i.slug}><span>{i.name} × {i.qty}</span><strong>{money((Number(i.price)||0)*i.qty)}</strong></div>)}<hr/><div className="checkout-total"><span>Toplam</span><strong>{money(total)}</strong></div><p>Bu sürümde ödeme ekranı demo olarak çalışır. Gerçek ödeme sağlayıcısı bağlantısı sonraki entegrasyonda yapılacaktır.</p></aside></div><Link href="/cart" className="back-link"><ArrowLeft size={15}/> Sepete dön</Link></main>}
