"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {ArrowLeft,Package,MapPin,Truck,CreditCard,CheckCircle2,Circle} from "lucide-react";
const money=n=>new Intl.NumberFormat("tr-TR",{style:"currency",currency:"TRY",maximumFractionDigits:0}).format(Number(n)||0);
const steps=["Sipariş alındı","Hazırlanıyor","Kargoya verildi","Teslim edildi"];
const addressLines=a=>a?[a.addressLine,a.neighborhood,a.district,a.city,a.postalCode].filter(Boolean):[];
export default function OrderDetail({params}){const [order,setOrder]=useState(null),[loading,setLoading]=useState(true);useEffect(()=>{let gone=false;Promise.resolve(params).then(({orderNo})=>{const no=decodeURIComponent(orderNo);return fetch(`/api/orders?orderNo=${encodeURIComponent(no)}`,{cache:"no-store"})}).then(r=>r.ok?r.json():Promise.reject()).then(d=>{if(!gone)setOrder(d.order)}).catch(()=>{if(!gone)setOrder(null)}).finally(()=>{if(!gone)setLoading(false)});return()=>{gone=true}},[params]);
if(loading)return <main className="account-page"><div className="account-hero"><small>ALYA HOMES / SİPARİŞ</small><h1>Yükleniyor…</h1></div></main>;
if(!order)return <main className="account-page"><div className="account-hero"><small>ALYA HOMES / SİPARİŞ</small><h1>Sipariş bulunamadı</h1><Link href="/account" className="text-link"><ArrowLeft size={16}/> Hesabıma dön</Link></div></main>;
const status=order.Status||"Sipariş alındı";const current=steps.indexOf(status);const history=order.history||[];const billing=order.BillingAddress||null;const shipping=order.ShippingAddress||null;const customerName=order.CustomerType==="Kurumsal"?(order.CompanyName||"Kurumsal müşteri"):([order.FirstName,order.LastName].filter(Boolean).join(" ")||order.Email||"Müşteri");
return <main className="account-page"><div className="account-hero"><small>ALYA HOMES / SİPARİŞ DETAYI</small><h1>{order.OrderNo}</h1><p>{new Date(order.CreatedAt).toLocaleDateString("tr-TR")} · {status}</p></div>
<div className="tracking-grid"><section className="account-card tracking-card"><div className="account-card-title"><Truck/><h2>Sipariş takibi</h2></div>{status==="İptal edildi"?<div className="cancelled-state"><strong>Sipariş iptal edildi</strong><span>Stok iadesi sisteme işlendi.</span></div>:<div className="tracking-steps">{steps.map((s,i)=><div className={`tracking-step ${i<=current?"done":""}`} key={s}>{i<=current?<CheckCircle2/>:<Circle/>}<div><strong>{s}</strong>{history.filter(h=>h.Status===s).slice(-1).map(h=><span key={h.CreatedAt}>{new Date(h.CreatedAt).toLocaleString("tr-TR")}</span>)}</div></div>)}</div>}{order.Carrier||order.TrackingNumber?<div className="shipment-box"><strong>Kargo bilgileri</strong>{order.Carrier&&<span>Kargo firması: {order.Carrier}</span>}{order.TrackingNumber&&<span>Takip numarası: {order.TrackingNumber}</span>}</div>:null}</section>
<section className="account-card"><div className="account-card-title"><CreditCard/><h2>Ödeme</h2></div><p>{order.PaymentMethod||"Belirtilmedi"}</p><span className="payment-status">Durum: {order.PaymentStatus||"Bekliyor"}</span></section></div>
<div className="account-grid"><section className="account-card"><div className="account-card-title"><Package/><h2>Ürünler</h2></div>{(order.items||[]).map(i=><div className="order-detail-line" key={i.ProductSlug+i.ProductName}><div><strong>{i.ProductName}</strong><span>{i.ProductCode||""} · {i.Quantity} adet</span></div><strong>{money(i.LineTotal??((Number(i.UnitPrice)||0)*(Number(i.Quantity)||0)))}</strong></div>)}</section><aside>
<div className="account-card"><div className="account-card-title"><MapPin/><h2>Müşteri / Fatura</h2></div><p><strong>{customerName}</strong></p>{order.CustomerType&&<p>Müşteri tipi: {order.CustomerType}</p>}{order.CustomerType==="Kurumsal"&&<>{order.TaxNumber&&<p>Vergi no: {order.TaxNumber}</p>}{order.TaxOffice&&<p>Vergi dairesi: {order.TaxOffice}</p>}</>}{order.CustomerType!=="Kurumsal"&&order.IdentityNumber&&<p>T.C. kimlik no: {order.IdentityNumber}</p>}{order.Email&&<p>{order.Email}</p>}{order.Phone&&<p>{order.Phone}</p>}{addressLines(billing).map((x,i)=><p key={`b${i}`}>{x}</p>)}</div>
<div className="account-card"><div className="account-card-title"><MapPin/><h2>Sevk / Teslimat</h2></div>{shipping?<>{shipping.recipientName&&<p><strong>{shipping.recipientName}</strong></p>}{shipping.phone&&<p>{shipping.phone}</p>}{addressLines(shipping).map((x,i)=><p key={`s${i}`}>{x}</p>)}{shipping.note&&<p>Not: {shipping.note}</p>}</>:<p>Adres bilgisi sipariş kaydında.</p>}<span className="payment-status">{order.SameAddress?"Fatura ve sevk adresi aynı":"Fatura ve sevk adresleri ayrı"}</span></div>
<div className="account-card order-total-card"><div><span>Ara toplam</span><strong>{money(order.Subtotal)}</strong></div><div><span>Kargo</span><strong>{money(order.Shipping)}</strong></div><div className="grand"><span>Toplam</span><strong>{money(order.Total)}</strong></div></div></aside></div><Link href="/account" className="back-link"><ArrowLeft size={15}/> Hesabıma dön</Link></main>}
