import {getShippingProviders,createShipment,trackShipment,getShipmentPayload} from '@/lib/shipping';
import sql from 'mssql';
export const runtime='nodejs';
export const dynamic='force-dynamic';
let poolPromise=null;
const configured=()=>Boolean(process.env.SQL_SERVER&&process.env.SQL_DATABASE&&process.env.SQL_USER&&process.env.SQL_PASSWORD);
async function pool(){if(!configured())return null;if(!poolPromise)poolPromise=sql.connect({server:process.env.SQL_SERVER,database:process.env.SQL_DATABASE,user:process.env.SQL_USER,password:process.env.SQL_PASSWORD,port:Number(process.env.SQL_PORT||1433),options:{encrypt:String(process.env.SQL_ENCRYPT||'false').toLowerCase()==='true',trustServerCertificate:String(process.env.SQL_TRUST_SERVER_CERTIFICATE||'true')}}).catch(e=>{poolPromise=null;throw e});return poolPromise}
export async function GET(req){try{const {searchParams}=new URL(req.url);const provider=String(searchParams.get('provider')||'').trim();const trackingNumber=String(searchParams.get('trackingNumber')||'').trim();if(provider&&trackingNumber)return Response.json({ok:true,result:await trackShipment(provider,trackingNumber)});return Response.json({providers:getShippingProviders()});}catch(e){return Response.json({error:e?.message||'Kargo servisi kullanılamadı'},{status:409})}}
export async function POST(req){try{const body=await req.json();const orderNo=String(body.orderNo||'').trim();const provider=String(body.provider||'').trim().toLowerCase();if(!orderNo||!provider)return Response.json({error:'orderNo ve provider gerekli'},{status:400});const p=await pool();if(!p)return Response.json({error:'SQL bağlantısı yapılandırılmamış'},{status:503});const q=await new sql.Request(p).input('orderNo',sql.NVarChar(60),orderNo).query(`SELECT TOP 1 o.*,c.Email,c.FirstName,c.LastName,c.Phone,c.AddressLine,c.City,c.District,c.PostalCode FROM dbo.AlyaOrders o LEFT JOIN dbo.AlyaCustomers c ON c.Id=o.CustomerId WHERE o.OrderNo=@orderNo`);if(!q.recordset.length)return Response.json({error:'Sipariş bulunamadı'},{status:404});const order=q.recordset[0];const shipment=await createShipment(provider,{...order,ShippingAddress:order.ShippingAddressJson?JSON.parse(order.ShippingAddressJson):null,BillingAddress:order.BillingAddressJson?JSON.parse(order.BillingAddressJson):null});return Response.json({ok:true,shipment,payload:getShipmentPayload(order)});}catch(e){return Response.json({error:e?.message||'Gönderi oluşturulamadı'},{status:409})}}
